export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const TOGGLE_PRODUCT_AMOUNT = 'TOGGLE_PRODUCT_AMOUNT';
export const GET_TOTAL_CART_QUANTITY = 'GET_TOTAL_CART_QUANTITY';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN';

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
