export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const TOGGLE_PRODUCT_AMOUNT = 'TOGGLE_PRODUCT_AMOUNT';
export const GET_TOTAL_CART_QUANTITY = 'GET_TOTAL_CART_QUANTITY';